# ~/.config/starship.toml

add_newline = false

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold dimmed white"

[git_branch]
disabled = true

[git_status]
disabled = true

[line_break]
disabled = true

[cmd_duration]
disabled = true

[username]
disabled = true
